import Link from 'next/link';

/**
 * 자동 생성 콘텐츠 고지.
 *
 * 이용약관 제3조의2 ①과 **같은 사실**을 글 본문에서 바로 보이게 한다. 구글의
 * helpful-content 자기평가는 자동화 사용이 "self-evident to visitors through disclosures"
 * 여야 한다고 요구하는데, 약관 조항 하나만으로는 방문자에게 self-evident하지 않다.
 *
 * 대상은 언어모델이 초안을 쓰는 두 곳뿐이다 — 게시판 글(`lib/board/generate.ts`)과
 * 가이드(`scripts/generate-guides.ts`). 상세 페이지의 서사(`lib/insights/*`)는 규칙 기반
 * 문자열 조립이라 여기 포함하지 않는다(섞으면 "상세도 AI가 쓴다"는 잘못된 인상을 준다).
 *
 * 모델명은 적지 않는다 — `GUIDE_MODEL` env로 바뀔 수 있어 즉시 허위 표기가 된다.
 */
export function AutoGeneratedNotice({ className = '' }: { className?: string }) {
  return (
    <p
      className={`rounded-lg border border-[var(--color-line)] bg-[var(--color-soft)] px-4 py-3 text-sm leading-relaxed text-[var(--color-muted-on-soft)] ${className}`}
    >
      이 글은 공공기관이 공개한 원문을 근거로 <strong className="font-semibold">언어모델이 초안을 작성</strong>하고,
      운영자가 검수한 뒤 게시했습니다. 근거가 된 원문의 출처는 글 하단에 표기했습니다.{' '}
      <Link href="/about" className="font-semibold text-[var(--color-blue)] underline-offset-2 hover:underline">
        운영·검수 방식
      </Link>
    </p>
  );
}
